name: Upload Python Package

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install poetry
          poetry install
      # - name: Bump version
      #   run: poetry version ${{  github.ref_name }}
      #   shell: bash
      - name: Lint
        run: poetry run poe lint
      - name: Test
        run: poetry run pytest
      - name: Stubs
        run: poetry run poe stubs
      - name: Build the package
        run: poetry build
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          packages_dir: ./dist
