name: Test
on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup requirements
        run: |
          pip install poetry && \
          poetry install

      - name: Test
        run: poetry run pytest
